homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml
  #packages: !include_dir_named packages

http:
  api_password: !secret api_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url
#  ip_ban_enabled: True
  login_attempts_threshold: 5

recorder:
  purge_interval: 2
  purge_keep_days: 5

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password
  protocol: 3.1
  birth_message:
    topic: 'hass/status'
    payload: 'online'
    qos: 1
    retain: true
  will_message:
    topic: 'hass/status'
    payload: 'offline'
    qos: 1
    retain: true

tts:
  platform: google
#  language: 'en'
  cache: true
#  cache_dir: /tmp/tts
  time_memory: 300

device_tracker:
#  - platform: owntracks
  - platform: mqtt_json
    devices:
      my_device: zanzito/RedmiNotePro/location

  - platform: nmap_tracker
    hosts: !secret nmap_hosts

  - platform: mqtt
    devices:
      doorbellNotifier: doorbellNotifier

  - platform: mqtt
    devices:
      mailNotifier: mailNotifier

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id

notify:
  - name: !secret telegram_name
    platform: telegram
#    api_key: !secret telegram_api_key
    chat_id: !secret telegram_chat_id
  - name: RedmiNotePro
    platform: zanzito
    device-name: RedmiNotePro
  - name: Nexus7
    platform: zanzito
    device-name: Nexus7
  - platform: webostv
    host: 192.168.123.134
    name: livingroom_tv
    filename: livingroom_tv.conf
  - platform: webostv
    host: 192.168.123.131
    name: bedroom_tv
    filename: bedroom_tv.conf

#shell_command:
#  backup_config: /home/homeassistant/.homeassistant/shell_scripts/backup_config.sh
#  announce_note3pro: 'curl "192.168.123.110:1035/?SPEAK={{ speak }}&@DONE@"'
#  announce_nexus7: 'curl "192.168.123.112:1035/?SPEAK={{ speak }}&@DONE@"'

#rest_command:
#  ringlight_off:
#    url: 'ws://192.168.123.161:81/'

ifttt:
  key: !secret ifttt_key

#ffmpeg:
#  ffmpeg_bin: /usr/bin/avconv
#  run_test: true

emulated_hue:
  type: alexa
  host_ip: !secret hue_host_ip
  listen_port: !secret hue_listen_port
#  expose_by_default: true
#  exposed_domains:
#    - light

panel_custom:
#  - name: dmp
#    sidebar_title: Digital Movie Poster
#    sidebar_icon: mdi:movie
#    config:
#      kodi: media_player.nvidia_shield_pro_spmc
#      api_pwd: !secret dmp_api_pwd
  - name: groundfloor
    sidebar_title: 00 Ground Floor
    sidebar_icon: mdi:home
    url_path: groundfloor
    config: !include groundfloor.yaml

  - name: upstairs
    sidebar_title: 01 Upstairs
    sidebar_icon: mdi:home
    url_path: upstairs
    config: !include upstairs.yaml

panel_iframe:
  youless:
    title: '03 YouLess LS110'
    icon: 'mdi:weather-sunset-down'
    url: !secret youless_url

  pvoutput:
    title: '04 PVOutput'
    icon: 'mdi:view-column'
    url: !secret pvoutput_url

#  ringlight:
#    title: '02 RingLight'
#    icon: 'mdi:google-circles-communities'
#    url: !secret ringlight_url

xiaomi_aqara:
  gateways:
    - mac:
      key: !secret xiaomi_key
  discovery_retry: 3

weather:
  - platform: buienradar
    name: buienradar
    latitude: 51.98
    longitude: 4.13
    forecast: True

feedreader:
    urls:
      - https://hasspodcast.io/feed/podcast

#octoprint:
#  host: !secret octoprint_ip
#  api_key: !secret octoprint_api

############
# INCLUDES #
############
light: !include lights.yaml
switch: !include switches.yaml
camera: !include cameras.yaml
group: !include groups.yaml
zone: !include_dir_list zones/
sensor: !include_dir_list sensors/
media_player: !include_dir_list media_player/
script: !include_dir_merge_named scripts
automation: !include automations.yaml
automation old: !include_dir_merge_list automation
input_boolean: !include_dir_merge_named input_booleans
input_number: !include_dir_merge_named input_numbers
input_select: !include_dir_merge_named input_select

###########
# ENABLES #
###########
frontend:
updater:
discovery:
conversation:
history:
logbook:
sun:
