- alias: Turn on dinner lights when there is movement
  trigger:
    platform: state
    # Motion Sensor 3
    entity_id: binary_sensor.motion_sensor_158d00010f8185
    to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: "below_horizon"
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_lamp_dinner
