- alias: "Ring Light Speed"
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: input_slider.ring_light_speed
  action:
    - service: mqtt.publish
      data_template:
        topic: "devices/ringlight/set"
        payload: '{"transition":{{ trigger.to_state.state | int }}}'
#        payload: '{{ trigger.to_state.state | string }}'
